# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MotiveMobileApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MotiveMobileApp

  pod 'react-native-config', :path => '../node_modules/react-native-config'

  target 'MotiveMobileAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
