# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MotiveMobileApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MotiveMobileApp
  pod 'FBSDKCoreKit', '~> 4.35.0'
  pod 'FBSDKLoginKit', '~> 4.35.0'
  pod 'FBSDKShareKit', '~> 4.35.0'
  pod 'Bolts', '~> 1.9.0'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'MotiveMobileAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end